### ISSUE TITLE
wrong math inside attraction class

### ISSUE THREAD

**Issue by joaodafonseca** [martinlindelof/ofxTraerPhysics#2]
Hi,

I found some issues with the math inside the attraction class. While porting some code from processing I notice that the springs were a behaving in a strange way. So by comparing attraction class from the processing library with yours I changed the apply() function to the following:

void Attraction::apply()
		{
			if ( on && ( !a->fixed || !b->fixed ) )
			{

				float a2bX = a->position.x - b->position.x;
				float a2bY = a->position.y - b->position.y;
				float a2bZ = a->position.z - b->position.z;

				float a2bDistanceSquared = a2bX*a2bX + a2bY*a2bY + a2bZ*a2bZ;

				if ( a2bDistanceSquared < distanceMinSquared )
					a2bDistanceSquared = distanceMinSquared;

				float force = k * a->mass * b->mass / a2bDistanceSquared;

				float length = (float)sqrt( a2bDistanceSquared );

				// make unit vector

				a2bX /= length;
				a2bY /= length;
				a2bZ /= length;

				// multiply by force

				a2bX *= force;
				a2bY *= force;
				a2bZ *= force;

				// apply

				if ( !a->fixed )a->force -= ofVec3f( -a2bX, -a2bY, -a2bZ );
				if ( !b->fixed )b->force += ofVec3f( a2bX, a2bY, a2bZ );
				
			}
		}

Now springs behave like a charm :)

**Comment by martinlindelof** [comment]
wow thanks haven't been using ofx in years. but updated it :)
