### ISSUE TITLE
Bug in Attraction class

### ISSUE THREAD

**Issue by pierrep** [martinlindelof/ofxTraerPhysics#3]
There's a bug in  Attraction::apply()

``
if ( !a->fixed )a->force -= ofVec3f( -a2bX, -a2bY, -a2bZ );
``
should be
``
if ( !a->fixed )a->force += ofVec3f( -a2bX, -a2bY, -a2bZ );
``

This causes particle attractions to be highly unstable.

**Comment by pierrep** [comment]
I see this is a known issue :)

> There seems to be an issue with Particle Attraction sometimes. They [particles] jiggle a bit to much.

**Comment by martinlindelof** [comment]
Thank you Pierre. there's a new attractor.cpp to pull.
